# Generated by Django 5.2 on 2025-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='special',
            field=models.CharField(default='New Arrival', max_length=50),
        ),
    ]
