# Generated by Django 5.2 on 2025-05-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='special',
        ),
        migrations.AddField(
            model_name='books',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='new_arrival',
            field=models.BooleanField(default=True),
        ),
    ]
